### ISSUE TITLE
Speak throws exception

### ISSUE THREAD

**Issue by tony37** [sugarlabs/speak#12]
Activity was updated to sugar3 and gstreamer 1.0. Apparently this change was not tested. 

espeak.py throws exception:

for i in Gst.ElementFactory.make('espeak','espeak').props.voices:

AttributeError: 'NoneType' object has no attribute 'props'.

Tested with Ubuntu 16.04 sucrose

**Comment by quozl** [comment]
It works fine for me on Ubuntu 16.04 with Sugar 0.110.  It requires install of dependent packages `gstreamer1.0-espeak`, `gir1.2-gstreamer-1.0` and `gir1.2-gst-plugins-base-1.0` and these are handled by apt when the activity is properly packaged.

Thanks for your opinion, but it was certainly tested, but not with Sugar 0.106 on Ubuntu 16.04.

**Comment by tony37** [comment]
How do you install Sugar 0.110 on Ubuntu 16.04? I looked at updating to 
Ubuntu 17.04 but first I would have to upgrade to 16.10. The update 
system reported a 8+ hour time to download the changes just for 16.10.

Tony

**Comment by quozl** [comment]
Get better internet or setup an instance of `approx` package on Debian or Ubuntu.

For you to install Sugar 0.110 on Ubuntu 16.04, see http://wiki.sugarlabs.org/go/Ubuntu#Ubuntu_16.04_Xenial_LTS says "Sugar 0.110 can be installed by careful addition of the Ubuntu 17.04 Zesty packages."  Obviously not all Ubuntu 17.04 packages are required.

For my customers, they get it pre-installed, as part of the service.
