### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by tony37** [sugarlabs/speak#13]
ASLO shows v49 but has v52 in older versions. The version in the repository is v53.

**Comment by quozl** [comment]
No, ASLO shows v52 for Browse on Sugar 0.110.  If you saw an offer of v49, you have probably hit the issue https://github.com/sugarlabs/aslo/issues/3 again.

Yes, the version in repository is v53; it requires a release bundle upload to ASLO, which isn't something I can do as far as I know.
